CD: use our npm token rather than trusted publishing.
For some reasons, this is not working for us anymore?!

Before we got:
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm notice publish Signed provenance statement with source and build information from GitHub Actions
npm notice publish Provenance statement published to transparency log: https://search.sigstore.dev/?logIndex=555275881
+ @opencor/libopencor@0.20250924.4

But now, we are getting:
npm error code ENEEDAUTH
npm error need auth This command requires you to be logged in to https://registry.npmjs.org/
npm error need auth You need to authorize this machine using `npm adduser`
npm error A complete log of this run can be found in: /home/runner/.npm/_logs/2025-09-25T20_52_02_257Z-debug-0.log
Error: Process completed with exit code 1.

This, even though we haven't changed anything!?