CI: use buildcache only on Windows and macOS.
Indeed, on Linux, we are currently getting the following error messages:
Post job cleanup.
/home/runner/work/libopencor/libopencor/buildcache/bin/buildcache -s
/home/runner/work/libopencor/libopencor/buildcache/bin/buildcache: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/runner/work/libopencor/libopencor/buildcache/bin/buildcache)
/home/runner/work/libopencor/libopencor/buildcache/bin/buildcache: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /home/runner/work/libopencor/libopencor/buildcache/bin/buildcache)
/home/runner/work/libopencor/libopencor/buildcache/bin/buildcache: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /home/runner/work/libopencor/libopencor/buildcache/bin/buildcache)
/home/runner/work/libopencor/libopencor/buildcache/bin/buildcache: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /home/runner/work/libopencor/libopencor/buildcache/bin/buildcache)

/home/runner/work/_actions/mikehardy/buildcache-action/v2/dist/webpack:/buildcache-action/node_modules/@actions/exec/lib/toolrunner.js:592
                error = new Error(`The process '${this.toolPath}' failed with exit code ${this.processExitCode}`);
^
Error: The process '/home/runner/work/libopencor/libopencor/buildcache/bin/buildcache' failed with exit code 1
    at ExecState._setResult (/home/runner/work/_actions/mikehardy/buildcache-action/v2/dist/webpack:/buildcache-action/node_modules/@actions/exec/lib/toolrunner.js:592:1)
    at ExecState.CheckComplete (/home/runner/work/_actions/mikehardy/buildcache-action/v2/dist/webpack:/buildcache-action/node_modules/@actions/exec/lib/toolrunner.js:575:1)
    at ChildProcess.<anonymous> (/home/runner/work/_actions/mikehardy/buildcache-action/v2/dist/webpack:/buildcache-action/node_modules/@actions/exec/lib/toolrunner.js:469:1)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
Also, at this stage, buildcache slows things down while it speeds them up quite a bit on macOS and somewhat on Windows.

qwe

qwe

qwe